### ISSUE TITLE
已加载数据的道具显示“未收录”

### ISSUE THREAD

**Issue by MuuuShin** [frto027/IsaacWikiDictionary#1]
最近从.28更新到.40，发现部分道具数据明明已经导入main.lua了，但是游戏中仍显示未收录
.28还反而正常显示
![image](https://user-images.githubusercontent.com/97760035/149574164-b429bc54-b2bd-48b3-b011-f68ef3ad3b9a.png)
![image](https://user-images.githubusercontent.com/97760035/149574110-0339e433-989b-4ae2-8639-c42bb9b2380c.png)

**Comment by frto027** [comment]
图鉴将游戏版本判定为AB+，为了和其它mod兼容，会删除忏悔的道具描述。
这个是因为游戏版本旧了。需要更新游戏版本，或使用1.0.35及以前版本的图鉴安装程序。

**Comment by MuuuShin** [comment]
> 图鉴将游戏版本判定为AB+，为了和其它mod兼容，会删除忏悔的道具描述。 这个是因为游戏版本旧了。需要更新游戏版本，或使用1.0.35及以前版本的图鉴安装程序。

好的，谢谢回答！
